name: CD Pipeline

on:
  push:
    tags:
      - '*.*.*'

jobs:
  docker-retag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Retag & Push
        run: |
          RAW_TAG="${GITHUB_REF#refs/tags/}"
          echo "Tagging version: $RAW_TAG"

          docker pull nspeerstra/portfolio-django:latest
          docker tag nspeerstra/portfolio-django:latest nspeerstra/portfolio-django:${RAW_TAG}
          docker push nspeerstra/portfolio-django:${RAW_TAG}

  # --- Stage 5: Deploy to MicroK8s (Tag push only) ---
  deploy:
    runs-on: self-hosted
    needs: docker-retag
    steps:
      - uses: actions/checkout@v3
      - name: Deploy manifests with MicroK8s
        run: |
          microk8s kubectl apply -k kubernetes/
